# Generated by Django 5.0.6 on 2024-06-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Sahib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Masin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=70)),
                ('model', models.CharField(max_length=70)),
                ('galeriya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.galeriya')),
                ('sahib', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masinlar', to='car.sahib')),
            ],
        ),
    ]
